import type { IncomingMessage, ServerResponse } from 'node:http'
import { randomBytes } from 'node:crypto'
import { isIP } from 'node:net'
import { constantTimeTextEqual, isRecommendedPasswordHash, isValidPasswordHash, verifyPasswordBounded } from '../auth/password.js'
import { LoginAttemptLimiter } from '../auth/rate-limiter.js'
import { createSessionToken, parseCookies, sessionCookie, sessionCookieName, verifySessionToken } from '../auth/session.js'
import type { SessionPayload } from '../auth/session.js'
import { readJson } from '../http/body.js'
import { jsonResponse } from '../http/response.js'
import { matchesRoute } from '../http/routing.js'
import { isRequestOriginAllowed, requestClientAddress } from '../http/security.js'
import { logEvent } from '../http/logger.js'
import { authAttemptStore, clearActiveSession, isActiveSession, setActiveSession } from '../db/repositories/auth.repository.js'

export type AuthConfig = {
  enabled: boolean
  username: string
  passwordHash: string
  sessionSecret: string
  sessionTtlSeconds: number
  maxAttempts: number
  attemptWindowMs: number
  lockoutMs: number
  secureCookie: boolean
  trustProxy: boolean
  appOrigin: string
  allowedIps: readonly string[]
}

type LoginBody = {
  username?: unknown
  password?: unknown
}

export function validateAuthConfig(config: AuthConfig, production: boolean): void {
  if (production && !config.enabled) throw new Error('Authentication cannot be disabled in production.')
  if (!config.enabled) return
  if (!config.username.trim()) throw new Error('AUTH_USERNAME is required when authentication is enabled.')
  if (!isValidPasswordHash(config.passwordHash)) throw new Error('AUTH_PASSWORD_HASH must be a valid scrypt hash generated by pnpm auth:hash.')
  if (production && !isRecommendedPasswordHash(config.passwordHash)) throw new Error('AUTH_PASSWORD_HASH uses outdated scrypt parameters; regenerate it with pnpm auth:hash.')
  if (Buffer.byteLength(config.sessionSecret) < 32) throw new Error('SESSION_SECRET must contain at least 32 bytes.')
  if (production && !config.appOrigin) throw new Error('APP_ORIGIN is required in production (for example https://interview.example.com).')
  if (config.appOrigin) {
    let origin: URL
    try {
      origin = new URL(config.appOrigin)
    } catch {
      throw new Error('APP_ORIGIN must be a valid origin (for example https://interview.example.com).')
    }
    if (origin.origin !== config.appOrigin) throw new Error('APP_ORIGIN must not contain a path, query string, or trailing slash.')
    if (production && origin.protocol !== 'https:') throw new Error('APP_ORIGIN must use HTTPS in production.')
  }
  if (config.allowedIps.some((value) => !isIP(value))) throw new Error('AUTH_ALLOWED_IPS must contain only valid IPv4 or IPv6 addresses.')
  if (production && !config.secureCookie) throw new Error('AUTH_COOKIE_SECURE cannot be disabled in production.')
}

export function createAuthHandler(config: AuthConfig) {
  const allowedIps = new Set(config.allowedIps.map(normalizeIp))
  const ipLimiter = new LoginAttemptLimiter(config.maxAttempts, config.attemptWindowMs, config.lockoutMs, authAttemptStore)
  const accountLimiter = new LoginAttemptLimiter(config.maxAttempts * 5, config.attemptWindowMs, config.lockoutMs, authAttemptStore)

  function sessionPayload(request: IncomingMessage): SessionPayload | 'development' | null {
    if (!config.enabled) return 'development'
    if (allowedIps.size && !allowedIps.has(normalizeIp(requestClientAddress(request, config.trustProxy)))) return null
    const token = parseCookies(request.headers.cookie)[sessionCookieName(config.secureCookie)]
    if (!token) return null
    const payload = verifySessionToken(token, config.username, config.passwordHash, config.sessionSecret)
    return payload && isActiveSession(payload.sid) ? payload : null
  }

  function authenticatedUsername(request: IncomingMessage): string | null {
    const payload = sessionPayload(request)
    return payload === 'development' ? payload : payload?.sub || null
  }

  async function handleRoutes(request: IncomingMessage, response: ServerResponse): Promise<boolean> {
    if (matchesRoute(request, 'GET', '/api/auth/session')) {
      const username = authenticatedUsername(request)
      jsonResponse(response, username ? 200 : 401, { authenticated: Boolean(username), ...(username ? { user: username } : {}) })
      return true
    }

    if (matchesRoute(request, 'POST', '/api/auth/login')) {
      if (!isRequestOriginAllowed(request, config.appOrigin)) {
        jsonResponse(response, 403, { error: '请求来源校验失败。' })
        return true
      }
      if (!config.enabled) {
        jsonResponse(response, 200, { authenticated: true, user: 'development' })
        return true
      }

      const ip = normalizeIp(requestClientAddress(request, config.trustProxy))
      if (allowedIps.size && !allowedIps.has(ip)) {
        logEvent('warn', 'auth_ip_denied', { ip })
        jsonResponse(response, 403, { error: '当前网络不允许登录。' })
        return true
      }
      const ipKey = `ip:${ip}`
      const accountKey = 'account:configured-user'
      const ipDecision = ipLimiter.consume(ipKey)
      if (!ipDecision.allowed) {
        logEvent('warn', 'auth_ip_locked', { ip, retryAfter: ipDecision.retryAfterSeconds })
        response.setHeader('Retry-After', String(ipDecision.retryAfterSeconds))
        jsonResponse(response, 429, { error: '登录尝试过于频繁，请稍后再试。', retryAfter: ipDecision.retryAfterSeconds })
        return true
      }
      const accountDecision = accountLimiter.consume(accountKey)
      if (!accountDecision.allowed) {
        const retryAfter = accountDecision.retryAfterSeconds
        logEvent('warn', 'auth_account_locked', { ip, retryAfter })
        response.setHeader('Retry-After', String(retryAfter))
        jsonResponse(response, 429, { error: '登录尝试过于频繁，请稍后再试。', retryAfter })
        return true
      }

      let body: LoginBody
      try {
        body = await readJson<LoginBody>(request, 8_192)
      } catch {
        jsonResponse(response, 400, { error: '登录信息格式无效。' })
        return true
      }
      const username = typeof body.username === 'string' ? body.username.trim() : ''
      const password = typeof body.password === 'string' ? body.password : ''
      const usernameMatches = constantTimeTextEqual(username, config.username)
      const passwordMatches = password.length <= 1_024 && await verifyPasswordBounded(password, config.passwordHash)
      if (!usernameMatches || !passwordMatches) {
        logEvent('warn', 'auth_login_failed', { ip })
        jsonResponse(response, 401, { error: '用户名或密码错误。' })
        return true
      }

      ipLimiter.reset(ipKey)
      accountLimiter.reset(accountKey)
      const sessionId = randomBytes(32).toString('base64url')
      const expiresAt = Date.now() + config.sessionTtlSeconds * 1_000
      setActiveSession(sessionId, expiresAt)
      const token = createSessionToken(config.username, sessionId, config.passwordHash, config.sessionSecret, config.sessionTtlSeconds)
      response.setHeader('Set-Cookie', sessionCookie(token, config.sessionTtlSeconds, config.secureCookie))
      logEvent('info', 'auth_login_success', { ip })
      jsonResponse(response, 200, { authenticated: true, user: config.username })
      return true
    }

    if (matchesRoute(request, 'POST', '/api/auth/logout')) {
      if (!isRequestOriginAllowed(request, config.appOrigin)) {
        jsonResponse(response, 403, { error: '请求来源校验失败。' })
        return true
      }
      const payload = sessionPayload(request)
      if (payload !== 'development' && payload) clearActiveSession(payload.sid)
      response.setHeader('Set-Cookie', sessionCookie('', 0, config.secureCookie))
      logEvent('info', 'auth_logout')
      jsonResponse(response, 204, {})
      return true
    }

    return false
  }

  return { authenticatedUsername, handleRoutes }
}

function normalizeIp(value: string): string {
  return value.startsWith('::ffff:') ? value.slice(7) : value
}
